In [3]:
a = 0
b = a
print(a+b)
print(a)

0
0


In [4]:
a = 0
b = 2
c = 3
print(a+b+c)

5


In [6]:
# Classification
from sklearn import tree
# Tree (Cay quyet dinh)
# buoc 1 thu thap du lieu training
# buoc 2 xu ly du lieu
# buoc 3 training model
# buoc 4 du doan ket qua
# buoc 5 danh gia ket qua hieu qua hay khong?
my_tree = tree.DecisionTreeClassifier() #Khoi tao cay quyet dinh
dac_trung = [['nhe','tb','tb','nhieu'],
             ['nang','thap','cao','it'],
             ['nhe','thap','cao','it'],
             ['nang','cao','cao','tb'],
             ['nhe','cao','cao','nhieu'],
             ['tb','thap','tb','nhieu'],
             ['tb','tb','tb','it'],
             ['nang','thap','thap','nhieu'],
             ]
quy_uoc  = [['1','3','3','7'],
             ['5','2','4','6'],
             ['1','2','4','6'],
             ['5','4','4','3'],
             ['1','4','4','7'],
             ['3','2','3','7'],
             ['3','3','3','6'],
             ['5','2','2','7'],
             ] # Mang 2 chieu
label = [0,1,1,0,0,0,0,1] #0:No 1:Yes

result = my_tree.fit(quy_uoc,label)

kq = result.predict([[1,4,3,6]])
print(kq)

[0]


In [7]:
import numpy as np
number_vector = np.array([1,2,3,4])
number_vector.shape

(4,)

In [8]:
number_matrix = np.array([[1,2,3],[4,5,6]])
number_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
number_matrix.shape

(2, 3)

In [10]:
number_3D_matrix = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]]
])

In [11]:
number_1D_zeros = np.zeros((7, ))
number_1D_zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [12]:
number_1D_zeros = np.zeros((7, 1))
number_1D_zeros

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [13]:
number_1D_zeros = np.zeros((7, 2))
number_1D_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
number_1D_zeros = np.zeros((2, 7))
number_1D_zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [15]:
number_1D_sevens = np.full((6, ), 7)
number_1D_sevens

array([7, 7, 7, 7, 7, 7])

In [17]:
number_2D_sevens = np.full((6, 7), 7)
number_2D_sevens

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [18]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
number_1D_range_10 = np.arange(10)
number_1D_range_10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
number_1D_range_2_20 = np.arange(2,10)
number_1D_range_2_20

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
number_1D_range_30 = np.arange(0, 30, 2)
number_1D_range_30

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [23]:
np.random.random((10,5))

array([[0.66864771, 0.25480552, 0.00806295, 0.47535483, 0.83131492],
       [0.35378605, 0.82162449, 0.47507311, 0.79459997, 0.34023298],
       [0.06333178, 0.29946602, 0.15919037, 0.08736782, 0.7687172 ],
       [0.40772685, 0.08641705, 0.73339565, 0.41426293, 0.46222188],
       [0.67838885, 0.14674553, 0.94718412, 0.77567608, 0.15178639],
       [0.77904557, 0.94317762, 0.04691695, 0.55625208, 0.6436223 ],
       [0.12673082, 0.56694758, 0.20566812, 0.12947649, 0.07128779],
       [0.73663709, 0.12871411, 0.73676521, 0.24235143, 0.2552295 ],
       [0.29278753, 0.47643704, 0.52760707, 0.06535509, 0.99603933],
       [0.84753769, 0.86808964, 0.40967765, 0.35981476, 0.59781603]])

In [25]:
number_2D = np.array([[4,5,6],[7,8,9]])
number_2D

array([[4, 5, 6],
       [7, 8, 9]])

In [26]:
number_2D[0]

array([4, 5, 6])

In [27]:
number_2D[1]

array([7, 8, 9])

In [28]:
number_2D[-1]

array([7, 8, 9])

In [29]:
number_2D[:,1]

array([5, 8])

In [1]:
number_1D = np.array([1,2,3])
number_1D + 3

NameError: name 'np' is not defined

In [36]:
number_1D = np.array([1,2,3,4])
for item in np.nditer(number_1D):
    print(item)

1
2
3
4


In [41]:
number_2D = np.random.random((3,3))
for item in np.nditer(number_2D):
    print(item)

0.10464541815467188
0.8314178420860243
0.370572916827969
0.8803327111403456
0.29962208484821673
0.32522945208285103
0.00319667789504241
0.8214944533937786
0.3135220896049925


In [43]:
numbers = np.arange(10)
for item in np.nditer(numbers,op_flags = ['readwrite']):
    item[...] = item**2
numbers

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [44]:
float_2D = np.random.random((2,2))
for x in np.nditer(float_2D, flags = ['external_loop'], order = 'F'):
    print(x)

[0.23896977 0.79931006]
[0.47815166 0.97685453]


In [45]:
float_2D = np.random.random((2,2))
for x in np.nditer(float_2D, flags = ['external_loop'], order = 'C'):
    print(x)

[0.98443661 0.37818418 0.00208386 0.19608034]


In [47]:
numbers = np.random.random((3,3))
flat_numbers = numbers.flatten()
flat_numbers

array([0.26894689, 0.64863573, 0.20518113, 0.99090051, 0.45122916,
       0.28723467, 0.90763429, 0.91840815, 0.92597925])

In [49]:
numbers_2D = np.array(([1,2],[3,4]))
numbers_3D_axis_0 = np.expand_dims(numbers_2D, axis=0)
numbers_3D_axis_0


array([[[1, 2],
        [3, 4]]])

In [52]:
numbers_2D = np.array(([1,2],[3,4]))
numbers_2D.T
transposed_numbers_2 = np.transpose(numbers_2D)
transposed_numbers_2

array([[1, 3],
       [2, 4]])

In [54]:
from numpy import linalg
A = np.array([1,2,3,4,5])
linalg.norm(A)
linalg.norm(A, ord = 1)

15.0

In [55]:
import tensorflow as tf
x = tf.constant(4)
y = tf.constant(5)
z = tf.add(x,y)
with tf.Session() as sess:
    # x, y ở đây mới bắt đầu có giá trị
    result = sess.run(z)
    print(z.eval())

ImportError: Could not find the DLL(s) 'msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads

In [3]:
import tensorflow as tf
with tf.compat.v1.Session() as sess:
    hello = tf.constant('hello world')
    print(sess.run(hello))

ImportError: Could not find the DLL(s) 'msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads

In [4]:
import tensorflow as tf
import timeit
from datetime import datetime
# Define a Python function.
def a_regular_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

# `a_function_that_uses_a_graph` is a TensorFlow `Function`.
a_function_that_uses_a_graph = tf.function(a_regular_function)

# Make some tensors.
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
# Call a `Function` like a Python function.
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()
assert(orig_value == tf_function_value)

def inner_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

# Use the decorator to make `outer_function` a `Function`.
@tf.function
def outer_function(x):
  y = tf.constant([[2.0], [3.0]])
  b = tf.constant(4.0)

  return inner_function(x, y, b)

# Note that the callable will create a graph that
# includes `inner_function` as well as `outer_function`.
outer_function(tf.constant([[1.0, 2.0]])).numpy()

def simple_relu(x):
  if tf.greater(x, 0):
    return x
  else:
    return 0

# `tf_simple_relu` is a TensorFlow `Function` that wraps `simple_relu`.
tf_simple_relu = tf.function(simple_relu)

print("First branch, with graph:", tf_simple_relu(tf.constant(1)).numpy())
print("Second branch, with graph:", tf_simple_relu(tf.constant(-1)).numpy())
# This is the graph-generating output of AutoGraph.
print(tf.autograph.to_code(simple_relu))
# This is the graph itself.
print(tf_simple_relu.get_concrete_function(tf.constant(1)).graph.as_graph_def())

ImportError: Could not find the DLL(s) 'msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads